// Achievement configuration data
export const ACHIEVEMENTS = [
  {
    id: 'first_harvest',
    name: '初次收穫',
    description: '收集第一個資源',
    emoji: '🎉',
    reward: 50,
    condition: (stats) => stats.totalResourcesCollected >= 1,
  },
  {
    id: 'egg_master',
    name: '雞蛋達人',
    description: '收集 50 顆雞蛋',
    emoji: '🥚',
    reward: 100,
    condition: (stats) => stats.eggsCollected >= 50,
  },
  {
    id: 'dairy_farmer',
    name: '奶牛農場主',
    description: '擁有 3 頭牛',
    emoji: '🐄',
    reward: 200,
    condition: (stats) => stats.cowCount >= 3,
  },
  {
    id: 'big_farmer',
    name: '農場主',
    description: '擁有 10 隻動物',
    emoji: '🐾',
    reward: 150,
    condition: (stats) => stats.totalAnimals >= 10,
  },
  {
    id: 'coin_master',
    name: '金幣達人',
    description: '累計賺取 1000 金幣',
    emoji: '💰',
    reward: 300,
    condition: (stats) => stats.totalCoinsEarned >= 1000,
  },
  {
    id: 'level3_building',
    name: '大農場主',
    description: '將任何建築升級到 3 級',
    emoji: '🏆',
    reward: 400,
    condition: (stats) => stats.maxBuildingLevel >= 3,
  },
  {
    id: 'crop_harvest',
    name: '作物豐收',
    description: '收穫 20 批作物',
    emoji: '🌾',
    reward: 200,
    condition: (stats) => stats.totalCropsHarvested >= 20,
  },
  {
    id: 'all_animals',
    name: '全收藏家',
    description: '擁有所有 5 種動物',
    emoji: '🐾',
    reward: 500,
    condition: (stats) => stats.animalTypesOwned >= 5,
  },
  {
    id: 'legend_farmer',
    name: '農場傳奇',
    description: '達到農場等級 5',
    emoji: '⭐',
    reward: 1000,
    condition: (stats) => stats.playerLevel >= 5,
  },
  {
    id: 'diligent_farmer',
    name: '勤勞農夫',
    description: '餵食動物 30 次',
    emoji: '🌿',
    reward: 150,
    condition: (stats) => stats.totalFeedingActions >= 30,
  },
];
